language: cpp

compiler:
    - clang

# This is the minimal amount of configuration required to install the build
# dependencies using the debian/control information. The fglrx package is there
# to provide AMD's CPU OpenCL implementation,
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq devscripts equivs fglrx
    - mk-build-deps -i -s sudo

# The --preserve-env and --preserve-envar PATH options are to allow
# dpkg-buildpackage to build the package using the compilers specified in the
# current Travis build environment.
script: debuild --preserve-env --preserve-envvar PATH -i -us -uc -b

