.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Rich Wareham <rjw57@cam.ac.uk>,
.\"
.TH DISPLAYDTCWT 1 "August 29, 2013"
.SH NAME
displayDTCWT \- show detected DT-CWT keypoints
.SH SYNOPSIS
.B displayDTCWT
.SH DESCRIPTION
This manual page documents briefly the
.B displayDTCWT
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBcldtcwt\fP will display a live feed from the first accessible video4linux
device and show the detected keypoints.
.SH AUTHOR
This program's original author was Tim Gale <timothy.gale@cantab.net>.
